config/routes.rb
Rails.application.routes.draw do
  root 'application#redirect_to_live'

 
  scope(:path => '/live') do
    get '/', to: 'chats#new'
    get '/login', to: 'student_sessions#new'
    get '/logon', to: 'students#new'
    delete '/logout', to: 'student_sessions#destroy'

  
    resource :admin_sessions, only: [:new, :create, :destroy], constraints: {format: :html}
    resource :student_sessions, only: [:new, :create, :destroy]
    resource :teacher_sessions, only: [:new, :create, :destroy]

    resources :admins, constraints: {format: :html}
    resources :teachers
    resources :students
    resources :chats, only: [:index, :new, :show], constraints: {format: :html}

    resources :admin_chattings, only: [:create, :destroy], constraints: {format: :json}
    resources :teacher_chattings, only: [:create, :destroy], constraints: {format: :json}
    resources :student_chattings, only: [:create, :destroy], constraints: {format: :json}

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/views/admins/_admin.html.erb
<% unless admin.root? %>
  <li class="list-group-item">
      <%= link_to "#{t 'name'} #{admin.name}, #{t 'mobile'} #{admin.mobile}", admin %>
  </li>
<% end %>

app/views/admins/_form.html.erb
<%= bootstrap_form_for(admin, local: true) do |form| %>
  <%= render 'share/errors', object: admin %>
  <% if admin.new_record? %>
    <%= form.text_field :mobile %>
  <% end %>
  <%= form.text_field :name %>
  <%= form.password_field :password %>
  <%= form.password_field :password_confirmation %>
  <%= form.submit t('commit') %>
<% end %>

app/views/admins/edit.html.erb
<div class="container">

  <h2><%= t '.title' %></h2>

  <%= render 'form', admin: @admin %>

</div>

app/views/admins/index.html.erb
<div class="container">

  <div class="jumbotron">
    <%= render 'share/simple_search', url: admins_path %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <p class="panel-title pull-left"><%= t 'admin' %></p>
      <% if current_admin&.root? %>
        <%= link_to t('new'), new_admin_path, class: 'btn btn-primary pull-right' %>
      <% end %>
      <div class="clearfix"></div>
    </div>

    <div class="panel-body">
      <%= will_paginate %>
    </div>

    <div class="list-group">
      <%= render(@admins) || t('no_admins') %>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<div class="container">

  <h2><%= t '.title' %></h2>

  <%= render 'form', admin: @admin %>

</div>

app/views/admins/show.html.erb
<div class="container">

  <div class="jumbotron">

    <a class="btn btn-primary btn-lg pull-right" href="<%= edit_admin_path %>">
      <span class="glyphicon glyphicon-cog"></span>
    </a>

    <p>
      <strong><%= t 'name' %></strong>:
      <%= @admin.name %>
    </p>

    <p>
      <strong><%= t 'mobile' %></strong>:
      <%= @admin.mobile %>
    </p>

    <p>
      <strong><%= t 'level' %></strong>:
      <%= Admin.to_level_title @admin.level %>
    </p>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <p class="panel-title pull-left"><%= t 'chat' %></p>
      <%= link_to t('more'),
                  chats_path,
                  class: 'btn btn-primary pull-right' %>
      <div class="clearfix"></div>
    </div>

    <div class="list-group">
      <%= render(@admin.chats[0..9]) || t('no_chats') %>
    </div>
  </div>

</div>