config/routes.rb
Rails.application.routes.draw do
  root 'application#redirect_to_live'

 
  scope(:path => '/live') do
    get '/', to: 'chats#new'
    get '/login', to: 'student_sessions#new'
    get '/logon', to: 'students#new'
    delete '/logout', to: 'student_sessions#destroy'

  
    resource :admin_sessions, only: [:new, :create, :destroy], constraints: {format: :html}
    resource :student_sessions, only: [:new, :create, :destroy]
    resource :teacher_sessions, only: [:new, :create, :destroy]

    resources :admins, constraints: {format: :html}
    resources :teachers
    resources :students
    resources :chats, only: [:index, :new, :show], constraints: {format: :html}

    resources :admin_chattings, only: [:create, :destroy], constraints: {format: :json}
    resources :teacher_chattings, only: [:create, :destroy], constraints: {format: :json}
    resources :student_chattings, only: [:create, :destroy], constraints: {format: :json}

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/chat.rb
class Chat < ApplicationRecord

  has_many :admin_chattings,
           foreign_key: :chat_id,
           inverse_of: :chat

  has_many :admins, through: :admin_chattings

  has_many :student_chattings,
           foreign_key: :chat_id,
           inverse_of: :chat

  has_many :students, through: :student_chattings

  has_many :teacher_chattings,
           foreign_key: :chat_id,
           inverse_of: :chat

  has_many :teachers, through: :teacher_chattings

  validates :name,
            presence: true,
            length: {maximum: 128}
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :logged_in
  before_action :set_chat, only: [:show]

  # GET /chats
  def index
    if current_student
      @chats = current_student.chats
    elsif current_teacher
      @chats = current_teacher.chats
    else
      if (mobile = params[:mobile])
        @chats = []
        student = Student.find_by_mobile mobile
        @chats += student.chats if student
        teacher = Teacher.find_by_mobile mobile
        @chats += teacher.chats if teacher
        admin = Admin.find_by_mobile mobile
        @chats += admin.chats if admin
      else
        @chats = Chat.all
      end
    end
  end

  # GET /chats/new
  def new
    @chat = Chat.new name: 'Coding'
    if @chat.save
      @app_id = '6c503009f94f42459ffa73cbd8a4c7de'
      @local_uid = if current_admin
                     current_admin.mobile % 100000
                   elsif current_teacher
                     current_teacher.id
                   elsif current_student
                     current_student.id
                   end
    else

    end
  end

  # GET /chats/:id
  def show

  end

  private

  def check_privilege
    redirect_back fallback_location: root_path, alert: t('no_privilege') unless current_admin ||
        (current_teacher && current_teacher.id == @chat.teacher_id) ||
        (current_student && current_student.id == @chat.student_id)
  end

  def set_chat
    @chat = Chat.find(params[:id])
    check_privilege
  end

  def chat_params
    @chat_params = params.require(:chat).permit(:name)
  end

end

app/views/chats/_chat.html.erb
<li class="list-group-item">
<%= link_to "#{t 'id'} #{chat.id},
        #{t 'name'} #{chat.name},
        #{t 'admin_count'} #{chat.admins.count},
        #{t 'teacher_count'} #{chat.teachers.count},
        #{t 'student_count'} #{chat.students.count}",
            chat %>
</li>

app/views/chats/index.html.erb
<div class="container">

  <% if current_admin %>
    <div class="jumbotron">
      <%= form_tag(chats_path, method: :get, html: {class: 'form-horizontal'}) do %>
        <div class="input-group input-group-lg">
        <span class="input-group-addon">
      <%= check_box_tag :should_pay_only, 1, params[:should_pay_only] %>
    </span>
          <%= text_field_tag :mobile,
                             nil,
                             class: 'form-control',
                             placeholder: t('.pattern'),
                             value: params[:mobile] || '' %>
          <div class="input-group-btn">
            <%= submit_tag t('search'), class: 'btn btn-primary' %>
          </div>
        </div><!-- /input-group -->
      <% end %>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <p class="panel-title pull-left"><%= t 'chat' %></p>
      <div class="clearfix"></div>
    </div>


    <div class="panel-body">
      <%= will_paginate if @chats && @chats.size > 0 && @chats.instance_of?(ActiveRecord::Relation) %>
    </div>

    <div class="list-group">
      <%= render(@chats) || t('no_chats') %>
    </div>
  </div>

</div>

app/views/chats/show.html.erb
<div class="container">

  <div class="jumbotron">

    <p>
      <strong><%= t 'chat' %></strong>
      <%= @chat.id %>
    </p>

    <p>
      <strong><%= t 'name' %></strong>
      <%= @chat.name %>
    </p>

    <% now = DateTime.now %>
    <% start_at = now %>
    <% end_at = now - 99.years %>

    <% @chat.admin_chattings.each do |c| %>
      <% start_at = c.start_at if start_at > c.start_at %>
      <% end_at = c.end_at if end_at < c.end_at %>
    <% end %>
    <% @chat.teacher_chattings.each do |c| %>
      <% start_at = c.start_at if start_at > c.start_at %>
      <% end_at = c.end_at if end_at < c.end_at %>
    <% end %>
    <% @chat.student_chattings.each do |c| %>
      <% start_at = c.start_at if start_at > c.start_at %>
      <% end_at = c.end_at if end_at < c.end_at %>
    <% end %>

    <p>
      <strong><%= t 'duration' %></strong>
      <%= "#{start_at} ~ #{end_at}" %>
    </p>

    <p>
      <strong><%= t 'chatters' %></strong>
      <% @chat.admins.each do |c| %>
        <%= link_to c.name, admin_path(c) %>,
      <% end %>
      <% @chat.teachers.each do |c| %>
        <%= link_to c.name, teacher_path(c) %>,
      <% end %>
      <% @chat.students.each do |c| %>
        <%= link_to c.name, student_path(c) %>,
      <% end %>
    </p>

  </div>

</div>