config/routes.rb
Rails.application.routes.draw do
  root 'application#redirect_to_live'

 
  scope(:path => '/live') do
    get '/', to: 'chats#new'
    get '/login', to: 'student_sessions#new'
    get '/logon', to: 'students#new'
    delete '/logout', to: 'student_sessions#destroy'

  
    resource :admin_sessions, only: [:new, :create, :destroy], constraints: {format: :html}
    resource :student_sessions, only: [:new, :create, :destroy]
    resource :teacher_sessions, only: [:new, :create, :destroy]

    resources :admins, constraints: {format: :html}
    resources :teachers
    resources :students
    resources :chats, only: [:index, :new, :show], constraints: {format: :html}

    resources :admin_chattings, only: [:create, :destroy], constraints: {format: :json}
    resources :teacher_chattings, only: [:create, :destroy], constraints: {format: :json}
    resources :student_chattings, only: [:create, :destroy], constraints: {format: :json}

    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  def self.degrees
    0..7
  end

  def self.to_degree_title(degree)
    case degree
    when 0
      'No'
    when 1
      'Bachelor'
    when 2
      'Master'
    when 3
      'Doctor'
    when 4
      'Post-doctor'
    when 5
      'Researcher'
    when 6
      'Associate-professor'
    when 7
      'Professor'
    else
      'Unknown'
    end
  end

  def self.degree_map
    Teacher.degrees.map{|i| [Teacher.to_degree_title(i), i]}
  end

  has_many :students,
           foreign_key: :teacher_id,
           inverse_of: :teacher

  has_many :teacher_chattings,
           foreign_key: :teacher_id,
           inverse_of: :teacher

  has_many :chats, through: :teacher_chattings


  has_secure_password

  validates :password,
            presence: true,
            length: {minimum: 8, maximum: 16},
            allow_nil: true

  validates :mobile,
            presence: true,
            format: {with: /\A\d{11}\z/},
            uniqueness: {case_sensative: true}

  validates :name,
            presence: true,
            length: {maximum: 128}

  validates :degree,
            presence: true,
            inclusion: {in: Teacher.degrees}

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :logged_in_admin, expect: [:show, :edit, :update]
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :only_self, only: [:edit, :update], unless: :current_admin
  before_action :only_self_or_own_student, only: [:show], unless: :current_admin

  # GET /teachers
  # GET /teachers.json
  def index
    if params[:mobile] && !params[:mobile].empty?
      @teachers = Teacher.where(mobile: params[:mobile].strip).paginate(
          page: params[:page], per_page: 10)
    else
      @teachers = Teacher.all.paginate page: params[:page], per_page: 10
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html {redirect_to @teacher, notice: t('creating_success')}
        format.json {render :show, status: :created, location: @teacher}
      else
        format.html {render :new, alert: t('creating_failed')}
        format.json {render json: @teacher.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html {redirect_to @teacher, notice: t('updating_success')}
        format.json {render :show, status: :ok, location: @teacher}
      else
        format.html {render :edit, alert: t('updating_failed')}
        format.json {render json: @teacher.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html {redirect_to teachers_url, notice: t('deleting_success')}
      format.json {head :no_content}
    end
  end

  private


  def only_self_or_own_student
    if current_student
      redirect_back fallback_location: root_path, alert: t('no_privilege') unless
          current_student.teacher_id == @teacher.id
    else
      redirect_back fallback_location: root_path, alert: t('no_privilege') unless
          current_teacher && current_teacher.id == @teacher.id
    end
  end

  def only_self
    redirect_back fallback_location: root_path, alert: t('no_privilege') unless
        current_teacher && current_teacher.id == @teacher.id
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def teacher_params
    params.require(:teacher).permit(:mobile, :name, :degree, :password, :password_confirmation)
  end
end

app/views/teachers/_form.html.erb
<%= bootstrap_form_for(teacher, local: true) do |form| %>
  <%= render 'share/errors', object: teacher %>
  <% if teacher.new_record? %>
    <%= form.text_field :mobile %>
  <% end %>
  <%= form.text_field :name %>
  <%= form.select :degree, Teacher.degree_map, {inlcude_blank: true} %>
  <%= form.password_field :password %>
  <%= form.password_field :password_confirmation %>
  <%= form.submit t 'commit' %>
<% end %>

app/views/teachers/_teacher.html.erb
<li class="list-group-item">
  <%= link_to "#{teacher.name},
  #{t 'mobile'} #{teacher.mobile},
  #{t 'degree'} #{teacher.degree},
  #{t 'chat_count'} #{teacher.chats.count}",
              teacher %>
</li>

app/views/teachers/edit.html.erb
<div class="container">

  <h2><%= t '.title' %></h2>

  <%= render 'form', teacher: @teacher %>

</div>

app/views/teachers/index.html.erb
<div class="container">

  <div class="jumbotron">
    <%= render 'share/simple_search', url: teachers_path %>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <p class="panel-title pull-left"><%= t 'teacher' %></p>
      <%= link_to t('new'),
                  new_teacher_path,
                  class: 'btn btn-primary pull-right' %>
      <div class="clearfix"></div>
    </div>

    <div class="panel-body">
      <%= will_paginate %>
    </div>

    <div class="list-group">
      <%= render(@teachers) || t('no_teachers') %>
    </div>
  </div>
</div>

app/views/teachers/new.html.erb
<div class="container">

  <h2><%= t '.title' %></h2>

  <%= render 'form', teacher: @teacher %>

</div>

app/views/teachers/show.html.erb
<div class="container">

  <div class="jumbotron">

    <a class="btn btn-primary btn-lg pull-right" href="<%= edit_teacher_path %>">
      <span class="glyphicon glyphicon-cog"></span>
    </a>

    <p>
      <strong><%= t 'teacher' %></strong>:
      <%= @teacher.name %>
    </p>

    <p>
      <strong><%= t 'mobile' %></strong>:
      <%= @teacher.mobile %>
    </p>

    <p>
      <strong><%= t 'degree' %></strong>:
      <%= Teacher.to_degree_title @teacher.degree %>
    </p>

    <p>
      <strong><%= t 'chat_count' %></strong>:
      <%= @teacher.chats.count %>
    </p>

  </div>

  <div class="panel panel-default">
    <div class="panel-heading">
      <p class="panel-title pull-left"><%= t 'chat' %></p>
      <%= link_to t('more'),
                  chats_path,
                  class: 'btn btn-primary pull-right' %>
      <div class="clearfix"></div>
    </div>

    <div class="list-group">
      <%= render(@teacher.chats[0..9]) || t('no_chats') %>
    </div>
  </div>

</div>